### ISSUE TITLE
[request] PvP Log timer.

### ISSUE THREAD

**Issue by FrozenBeard** [NoChanceSD/PvPManager#153]
Ahoy

requesting something incredibly basic, a basic cooldown timer before the PvP Log punishments happen, something we can configure. 

So if another plugin antecedently kicks the player, they have time to relog quickly.

**Comment by FrozenBeard** [comment]
@NoChanceSD Bump.

**Comment by NoChanceSD** [comment]
I don't think this is doable because after the players leaves we can no longer modify his inventory or kill him while offline(without using version specific code anyway, which i only use on the premium version).
So basically if a player leaves and doesn't come back until next restart he can't be punished. Then there's also the possibility of just saving that to a file so it lasts between restarts but what if he never comes back. Far from basic imo but i will think about it better.

**Comment by FrozenBeard** [comment]
Not like that, when you issue a punishment, you do it normally. But instead of issuing it instantly you put it into a queue/timer to happen in the future (say 30 seconds) so if they are kicked by accident they have a 30 second buffer to log in again.

**Comment by NoChanceSD** [comment]
I know, what i'm saying is what if it wasn't an accident, then the timer runs out, the plugin realizes the player didn't come back and it has no way of killing them or dropping their items without NMS because the player is offline(I think, it has been a while but it didn't use to be possible).

I just remembered that NPCs basically do what you want though, it spawns an NPC with everything the player has for x seconds, if the NPC gets killed while they are offline they lose all their items and die. However if they relog and the NPC is fine nothing happens. That's currently only on premium though.

**Comment by FrozenBeard** [comment]
I tried the NPC version, but it was so buggy it only took 2 days for people to abuse to to dupe items, I cant have item duping on a survival server.

**Comment by NoChanceSD** [comment]
I use it on my survival server too, no duping issues as far as i know, at least none reported.
