### ISSUE TITLE
You can place redstone torches when PvP tagged

### ISSUE THREAD

**Issue by FrozenBeard** [NoChanceSD/PvPManager#191]
Using Paper 1.12.2

Claim protection is GriefPrevention. 
Video:
https://imgur.com/a/D91gMFw

**Comment by NoChanceSD** [comment]
That message comes from GriefPrevention, you can find it in their messages.yml under "NoBuildPvP", you should set CombatTimeoutSeconds in their config to 0, otherwise you have 2 plugins doing the same thing and you don't know which one is the issue.
Either way, the torch placement is being blocked, it's not placed but the redstone update detector still reacts to it, this would probably have to be fixed by spigot imo.
